<?php
/**
 * @author JKetelaar
 */

namespace AppBundle\Repository;

/**
 * OrderAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
