security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            provider: fos_userbundle
            form_login:
                check_path: /users/login_check
                login_path: /users/login
                success_handler: authentication.handler.login_success_handler

            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                always_remember_me: true

    access_control:
    - { path: ^/users/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/users/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/users/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

#    - { path: ^/api/users/current, role: IS_AUTHENTICATED_ANONYMOUSLY }

    - { path: ^/admin/, role: ROLE_ADMIN }

    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }