parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests,Service,Listener}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    date_time.normalizer:
        class: AppBundle\Service\Normalizers\DateTimeNormalizer
        tags:
        - { name: serializer.normalizer }

    cart_helper:
        class: AppBundle\Service\CartHelper
        arguments: ['@Doctrine\ORM\EntityManagerInterface']

    purchase_helper:
        class: AppBundle\Service\PurchaseHelper
        arguments: ['@Doctrine\ORM\EntityManagerInterface']

    file_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['%upload_directory%']

    form_error_helper:
        class: AppBundle\Service\FormErrors

    guest_id_listener:
        class: AppBundle\Listener\GuestIDListener
        arguments: ['@cart_helper']
        tags:
            - {
                name: kernel.event_listener,
                event: kernel.response,
                method: onKernelResponse
              }

    app.controller.register:
        class: AppBundle\Controller\User\RegistrationController
        arguments: ['@service_container']
        public: true